"""Fix foreign key error

Revision ID: 682c38ed2064
Revises: 8571a003b64a
Create Date: 2025-03-06 16:11:16.890238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682c38ed2064'
down_revision: Union[str, None] = '8571a003b64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_datasets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'saved_datasets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_datasets', type_='foreignkey')
    op.drop_column('saved_datasets', 'user_id')
    # ### end Alembic commands ###
